"""
NagarMind v2 — Chatbot API Route
backend/app/api/chatbot.py

Add to main.py:
  from app.api.chatbot import router as chatbot_router
  app.include_router(chatbot_router, prefix="/api/chatbot", tags=["Chatbot"])
"""

import logging
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import Optional

from app.core.database import get_db
from app.middleware.auth_middleware import require_citizen
from app.services.complaint_pipeline import run_pipeline
from app.services.chatbot_agent import chat_with_agent, clear_session

router = APIRouter(tags=["chatbot"])
logger = logging.getLogger(__name__)

# Track which thread_ids have already been submitted (prevent double inserts)
_submitted: set[str] = set()


class ChatMessageRequest(BaseModel):
    message: str
    thread_id: str       # UUID generated by frontend per complaint session
    language: str = "en"
    latitude: float = 28.6139
    longitude: float = 77.2090


class ChatMessageResponse(BaseModel):
    reply: str
    stage: str           # greet | gather | confirm | submitted
    complaint_id: Optional[str] = None


@router.post("/message", response_model=ChatMessageResponse)
async def chat_message(
    body: ChatMessageRequest,
    background_tasks: BackgroundTasks,
    payload=Depends(require_citizen),
    pool=Depends(get_db),
):
    citizen_id = str(payload["sub"])

    # Get citizen's ward
    citizen = await pool.fetchrow(
        "SELECT ward_id FROM citizens WHERE citizen_id=$1", citizen_id
    )
    if not citizen:
        raise HTTPException(404, "Citizen not found")

    ward_id = citizen["ward_id"]

    # Run agent
    result = await chat_with_agent(
        thread_id=body.thread_id,
        user_message=body.message,
        citizen_id=citizen_id,
        ward_id=ward_id,
        language=body.language,
        latitude=body.latitude,
        longitude=body.longitude,
    )

    complaint_id = None

    # If agent completed — insert complaint once
    if (
        result["stage"] == "submitted"
        and result.get("complaint_payload")
        and body.thread_id not in _submitted
    ):
        _submitted.add(body.thread_id)
        cp = result["complaint_payload"]

        try:
            cid = await pool.fetchval(
                """INSERT INTO complaints
                   (citizen_id, ward_id, title, description,
                    category, latitude, longitude, address,
                    photo_urls, voice_transcript, status, submitted_at)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'{}',NULL,'submitted',NOW())
                   RETURNING complaint_id""",
                citizen_id, ward_id,
                cp.get("title", "Civic Issue"),
                cp.get("description", ""),
                cp.get("category", "other"),
                cp.get("location_lat", 28.6139),
                cp.get("location_lng", 77.2090),
                cp.get("location_address", ""),
            )
            complaint_id = str(cid)

            # Initial status history
            await pool.execute(
                """INSERT INTO complaint_status_history
                   (complaint_id, old_status, new_status, changed_by, changed_by_role, note)
                   VALUES ($1, NULL, 'submitted', $2, 'citizen', 'Submitted via AI chatbot')""",
                complaint_id, citizen_id,
            )

            # Notify citizen
            citizen_row = await pool.fetchrow(
                "SELECT phone_number FROM citizens WHERE citizen_id=$1", citizen_id
            )
            from app.services.notification_service import notify_citizen
            if citizen_row:
                await notify_citizen(
                    pool, citizen_id, citizen_row["phone_number"],
                    complaint_id, "complaint_submitted",
                    "Complaint Submitted ✓",
                    f"Your complaint '{cp.get('title')}' has been received via chatbot.",
                    language=body.language, send_sms=False,
                )

            # AI classification pipeline
            background_tasks.add_task(run_pipeline, pool, complaint_id)
            logger.info(f"Chatbot complaint submitted: {complaint_id}")

        except Exception as e:
            logger.error(f"Chatbot DB insert failed: {e}")
            _submitted.discard(body.thread_id)

    return ChatMessageResponse(
        reply=result["reply"],
        stage=result["stage"],
        complaint_id=complaint_id,
    )


@router.delete("/session/{thread_id}")
async def clear_chat_session(thread_id: str, payload=Depends(require_citizen)):
    """Clear session when user starts a new complaint."""
    clear_session(thread_id)
    _submitted.discard(thread_id)
    return {"cleared": True}